from .itask import ITask
from datetime import datetime


class TaskMangaNotify(ITask):
    def setup(self) -> None:
        pass
    def teardown(self) -> None: ...
    def run(self) -> None: ...
    @property
    def first_delay(self) -> float: ...
    @property
    def interval(self) -> float: ...
    @property
    def latest_run(self) -> datetime: ...
    @property
    def name(self) -> str: ...
