from __future__ import annotations
from contextlib import contextmanager
from typing import Generator, Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from fazbot import Asset, Bot, Config, Heartbeat, Logger
    from fazbot.db.fazbot import IFazBotDatabase


class Core(Protocol):
    """<<interface>>"""
    def start(self) -> None: ...
    def stop(self) -> None: ...
    @contextmanager
    def enter_asset(self) -> Generator[Asset]: ...
    @contextmanager
    def enter_bot(self) -> Generator[Bot]: ...
    @contextmanager
    def enter_config(self) -> Generator[Config]: ... 
    @contextmanager
    def enter_fazbotdb(self) -> Generator[IFazBotDatabase]: ... 
    @contextmanager
    def enter_heartbeat(self) -> Generator[Heartbeat]: ...
    @contextmanager
    def enter_logger(self) -> Generator[Logger]: ...

