from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from fazbot import Bot, Config, Heartbeat, ImageAsset, Logger, Userdata


class Core(Protocol):
    """<<interface>>"""
    def start(self) -> None: ...
    def stop(self) -> None: ...
    @property
    def get_asset_threadsafe(self) -> ImageAsset: ...
    @property
    def bot(self) -> Bot: ...
    @property
    def get_config_threadsafe(self) -> Config: ...
    @property
    def heartbeat(self) -> Heartbeat: ...
    @property
    def logger(self) -> Logger: ...
    @property
    def userdata(self) -> Userdata: ...
